# dyff between <(yq . <(helm show values metallb/metallb --version v0.15.2)) <(yq eval '. * load("values.yaml")' <(helm show values metallb/metallb --version v0.15.2))
# vim -O <(helm show values metallb/metallb --version v0.15.2) values.yaml
