---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
spec:
  interval: 60m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
    - kind: Secret
      name: cert-manager-secrets
