apiVersion: v1
kind: Secret
metadata:
    name: evanstest
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tAU+KPB5jY01xRONh5Y7AyeEwmM=,iv:IJd5wwrMzpYNocbIBVPNqVsbQ59/aq1wWjzc6Now6rM=,tag:2wnfPIr7F2CX1yD7psyf9A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oWBVRk34tsXtOgZ+Q+IycetHuiq0M03rUq9nZz4vL91zsQcQXzvBpA==,iv:xinDtqLIR31MYBoRl6VdzxXLr/Zoa6lu4UBlD2eDPr4=,tag:ML5UQrTeGuokODJhKllSLA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:lJfWdtA5bOMAfj/QxQqNW9S6JX1TL7wsD+GPV+cQa2bJLA==,iv:GbuU4QJsoj/YIbDIUcVIE7FEGJHlYdO9lWn1AX/5iWA=,tag:tDCyGAMezYOvWYjme7gQqQ==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cXREZVYrUVVmK05RL3BJ
            eHVZRDVXaDdLQk1nTVJKWWdvTjROSjdPbGhRCjhSUHFZT28wUmV3QUkrZVhQUUV6
            VG13L0V2b3hCNVlhLzZzYTEzbTNIaTQKLS0tIHIxK1h3YUkySGxsSDFlbWQzZFNp
            U1YvTXA3c3JhZndOdnpMaDU0YnI2UUEK5p8wkBlt9cZg5pL6Fu8Y79CkmlWSqCPg
            tQF+ozNSIsem7y8K7EYrvPgO6z5fdiWT15jPcB+P/sLkUYOS494C0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T01:33:45Z"
    mac: ENC[AES256_GCM,data:JfX6vb59JvpEIohJ2z6ouijtoYcTx3jHe0pmGKxlRuaXTeoFk9hbKXY2dAwG8tw6xnfmpQEssVulIVg2NG3/o3tVX5LsIGKnzaZtD/8oucjC22VYRj4zb/sBHKG6rR3Byq9FmMrOUS/ttPZCIqu2XY08UlghjDMtl8N467iE3gU=,iv:UkJ6WnOUZVILaZ4h1yq002ZVGobN5ErAd5qmx2UfCmI=,tag:RIaJIeIX03J+u7mLy6EjcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
