# https://longhorn.io/docs/1.10.1/advanced-resources/security/volume-encryption/
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-crypto
    namespace: longhorn-system
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:tNyvfH4+d3NDeALXd1jM3tlDpeLXkH7/xeC/+wxNsg==,iv:WgV/2kG3vxAR0REffk9HR8spql3S1AKJv1zOzwIDtdk=,tag:Z/zjyM+f84y8q5FG6/CBjg==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:8nkydSeD,iv:ZOx4NJZp2qFyd9GBJeeCuJ0aeuR1+tETwBMBklOQxmw=,tag:AhaHWIiifpewTa6DG3+W7g==,type:str]
    CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:W8pMYHqIr4d5IVu22C8f,iv:okjoN2Maj2jjDVu1xZ+nrZBj5bIkXWk7BrFCR2xWdx0=,tag:qTEAo2SwwtaQsSMJUd5+Bw==,type:str]
    CRYPTO_KEY_HASH: ENC[AES256_GCM,data:IB6N5DqO,iv:fQsUikbBwbzOoTau55iyUjVMOx074zNIB0GF1EtFDKQ=,tag:Z9oyIfRnQehCgrB5EAahFw==,type:str]
    CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:usEA,iv:AwWx9xIrZQmO8vUO3qCZMnDumSWfwQeOMvuJiyONUmc=,tag:VMMvrf0pB0AWe7o5dgxE7Q==,type:str]
    CRYPTO_PBKDF: ENC[AES256_GCM,data:O6RyT/2Keg==,iv:9heBoa9wGb6J/hBNe65am/owrY8yXn+A8lBSWSjF1TI=,tag:5wGv8iUSBpTA8uHn8xBqNg==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbHpvU0YxVnpLSTJ4cTJk
            M2VnOGpWSElYMExtWDdaL0xERnpVMDNNbFdFCnBBN3hndC9SMjhhVHFabnREZVBo
            dlVzZmFjNTFNbUlxNDNzMi9wN2NHWVEKLS0tIGhRU2hMK2txb1hkV1JDV1pRc2Fi
            SXFlTjVGU3pHZFR1ZVErZnVzN0lRMDAKR5JkeqjHN4w5PUfEMc43w4IGWe4fG0yv
            yQtLlnJyTE4VVofWf6tBz+knqKARPL7zTa+XrPFfRA3dMg8Gt+L/HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T23:25:57Z"
    mac: ENC[AES256_GCM,data:f0UJzf0vrb5kQgvPHnLhGmJu4dZfMiCJleQQnL0iOFvQX99GzboXv/RmoYCA/5sMCGg+slCmbjurejzSUD6IaD0CeqZi+fbPoRjbqLDZWMgi+ZR6amlNs+54PlpT6VnaOwCWTbX0FOXfjpllOudNLtFUJghjvdsI4VtycrkK6MM=,iv:5PU2PNDPpu1tnpOr8S/P2l4TopkW6udNkWhvgJ3QOQg=,tag:uc+V2D4T9DSoIEr1HXRYAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
