---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 60m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values
    - kind: Secret
      name: ingress-nginx-secrets
