controller:

  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    allow-snippet-annotations: "true"
    limit-req-status-code: "429"

    # Uncomment this if you DGAF about security and you want to have variables in your redirect urls.
    # https://github.com/kubernetes/ingress-nginx/issues/11175
    # annotations-risk-level: Critical

  ingressClassResource:
    default: true
  replicaCount: 3
  service:

    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.13/guide/service/annotations/
    annotations:

      # If you have a development cluster, you should uncomment this to make ingresses internal (private) by default.
      # At some point this will be deprecated in favor of: service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"

      # An NLB is required for: exposing TCP services, passing real IP addresses through to the ingress, and creating internal load balancers.
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

    externalTrafficPolicy: "Local"

  metrics:
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true

# Example of how to expose a TCP service
# tcp:
#   55001: "demo-bot/rabbitmq:5672"
