controller:

  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    allow-snippet-annotations: "true"
    limit-req-status-code: "429"

    # TODO: Why did we enable this once?
    # annotations-risk-level: Critical

  ingressClassResource:
    default: true
  replicaCount: 3
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    externalTrafficPolicy: "Local"

  metrics:
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true

# Example of how to expose a TCP service
# tcp:
#   55001: "demo-bot/rabbitmq:5672"
