controller:

  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    allow-snippet-annotations: "true"
    limit-req-status-code: "429"
    annotations-risk-level: Critical

  ingressClassResource:
    default: true
  replicaCount: 3
  service:
    externalTrafficPolicy: "Local"

  metrics:
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true
