# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Setting namespace here will ensure that all objects managed by this Kustomization will explicitly be deployed to this namespace. You don't need to put specify `namespace:` anywhere else if you do this.
# This is deployed to the same namespace as rook-ceph, per these instructions:
# https://rook.io/docs/rook/latest-release/Helm-Charts/ceph-cluster-chart/#release
namespace: rook-ceph

resources:
  - release.yaml
configMapGenerator:
  - name: rook-ceph-cluster-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: rook-ceph-cluster-secrets
    files:
      - values.yaml=helm_secrets.yaml
configurations:
  - kustomizeconfig.yaml
