apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.17.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph-cluster-values
    - kind: Secret
      name: rook-ceph-cluster-secrets
