apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

resources:
  - gatewayclass.yaml
  - envoyproxy-public.yaml
  - envoyproxy-private.yaml
  - gateway-public.yaml
  - gateway-private.yaml
  - httproute-healthz-public.yaml
  - httproute-healthz-private.yaml
