{
 "title": "AWS Load Balancer Controller",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_active_workers, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Controller Reconcile Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (controller, result) (rate(controller_runtime_reconcile_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n  sum by (le, controller) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{controller}} - 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, controller) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{controller}} - 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, controller) (\n    rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{controller}} - 0.99"
    }
   ]
  },
  {
   "title": "Controller Max Concurrent Reconciles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (controller) (controller_runtime_max_concurrent_reconciles{job=\"$job\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(controller_runtime_reconcile_errors_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Webhook Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (webhook, code) (rate(controller_runtime_webhook_requests_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{webhook}} - {{code}}"
    }
   ]
  },
  {
   "title": "Controller Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (controller) (controller_runtime_active_workers{job=\"$job\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "AWS Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "AWS Api Calls Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (operation, status_code) (rate(aws_api_calls_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{operation}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "AWS Api Calls Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n  sum by (le, operation) (\n    rate(aws_api_call_duration_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{operation}} - 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, operation) (\n    rate(aws_api_call_duration_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{operation}} - 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, operation) (\n    rate(aws_api_call_duration_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{operation}} - 0.99"
    }
   ]
  },
  {
   "title": "AWS Api Retries Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n  sum by (le, operation) (\n    rate(aws_api_call_retries_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{operation}} - 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, operation) (\n    rate(aws_api_call_retries_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{operation}} - 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, operation) (\n    rate(aws_api_call_retries_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{operation}} - 0.99"
    }
   ]
  },
  { "title": "Rest Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Rest Client Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(rest_client_requests_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Rest Client Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, verb)(\n    rate(rest_client_request_duration_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{verb}} - 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, verb) (\n    rate(rest_client_request_duration_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{verb}} - 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, verb) (\n    rate(rest_client_request_duration_seconds_bucket{job=\"$job\"}[5m])\n  )\n)",
     "legendFormat": "{{verb}} - 0.99"
    }
   ]
  }
 ]
}