{
 "title": "Karpenter Performance v1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_time_seconds_count{job=\"karpenter\"}, controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Termination Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(karpenter_nodes_termination_duration_seconds{quantile=\"0\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(karpenter_nodes_termination_duration_seconds{quantile=\"0.5\"})",
     "legendFormat": "P50"
    },
    {
     "expr": "max(karpenter_nodes_termination_duration_seconds{quantile=\"0.9\"})",
     "legendFormat": "P90"
    },
    {
     "expr": "max(karpenter_nodes_termination_duration_seconds{quantile=\"0.99\"})",
     "legendFormat": "P99"
    },
    {
     "expr": "max(karpenter_nodes_termination_duration_seconds{quantile=\"1\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Pod Startup Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(karpenter_pods_startup_duration_seconds{quantile=\"0\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(karpenter_pods_startup_duration_seconds{quantile=\"0.5\"})",
     "legendFormat": "P50"
    },
    {
     "expr": "max(karpenter_pods_startup_duration_seconds{quantile=\"0.9\"})",
     "legendFormat": "P90"
    },
    {
     "expr": "max(karpenter_pods_startup_duration_seconds{quantile=\"0.99\"})",
     "legendFormat": "P99"
    },
    {
     "expr": "max(karpenter_pods_startup_duration_seconds{quantile=\"1\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Latency [$controller]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
     "legendFormat": "Min"
    },
    {
     "expr": "histogram_quantile(0.5, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[10m]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"karpenter\"}[10m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}