---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 60m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: nginx
      version: 21.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: nginx-values
    - kind: Secret
      name: nginx-secrets
