replicaCount: 3
pdb:
  minAvailable: "51%"
cloneStaticSiteFromGit:
  enabled: false
  repository: ""
  branch: ""
## @param serverBlock Custom server block to be added to NGINX configuration
## PHP-FPM example server block:
## serverBlock: |-
##   server {
##     listen 0.0.0.0:8080;
##     root /app;
##     location / {
##       index index.html index.php;
##     }
##     location ~ \.php$ {
##       fastcgi_pass phpfpm-server:9000;
##       fastcgi_index index.php;
##       include fastcgi.conf;
##     }
##   }
##
serverBlock: ""
ingress:
  enabled: true
  hostname: website.project1-dev.devops.coop
  path: /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls: true
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
