apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-custom-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/cert-manager-custom-resources
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
