apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-messaging-topology-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: rabbitmq-cluster-operator
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/rabbitmq-messaging-topology-operator
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  suspend: false
