---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-values
    - kind: Secret
      name: metrics-server-secrets
