# https://cert-manager.io/docs/configuration/acme/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: hostmaster@devops.coop

    # Default profile is "classic", but cert-manager docs uses tlsserver, which reflects "the latest recommendations from the CA/Browser Forum Baseline Requirements, as well as general trends within the WebPKI community."
    # https://cert-manager.io/docs/configuration/acme/#acme-certificate-profiles
    # https://letsencrypt.org/docs/profiles/#tlsserver
    profile: tlsserver

    # Let's Encrypt's prod server
    # https://letsencrypt.org/getting-started/#selecting-and-operating-an-acme-client-yourself
    server: https://acme-v02.api.letsencrypt.org/directory

    # This is supposed to have a default of "tls.key", but apparently that doesn't work, because I get this error when I don't specify it:
    #
    # $ k get ks -n flux-system cert-manager-custom-resources
    # NAME                            AGE   READY   STATUS
    # cert-manager-custom-resources   64m   False   ClusterIssuer/cert-manager/letsencrypt dry-run failed (Invalid): ClusterIssuer.cert-manager.io "letsencrypt" is invalid: spec.acme.privateKeySecretRef: Required value...
    #
    # https://github.com/cert-manager/cert-manager/issues/7845
    privateKeySecretRef:
      name: tls.key

    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
        selector:
          matchLabels:
            "use-http01-solver": "true"
      - dns01:
          cloudflare:
            email: hostmaster@devops.coop
            apiTokenSecretRef:
              name: cloudflare-apikey-secret
              key: apikey
