apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Setting namespace here will ensure that all objects managed by this Kustomization will explicitly be deployed to this namespace. You don't need to put specify `namespace:` anywhere else if you do this.
namespace: app-template

resources:
  - example.yaml
